### ISSUE TITLE
foam run should use multiprocessing as an option

### ISSUE THREAD

**Issue by RobertArbon** [RedesignScience/foam#19]

**Comment by amardt** [comment]
I have a question regarding the multiprocessing:
One could do it this way:
`from functools import partial
from multiprocessing import Pool

def get_cov_estimators(input_path, options, lags):


    ftraj = get_data(input_path, options)
    cov_est = calculate_covariance(ftraj, options.covariance, lags)
    return cov_est


def accumulate_covariance(options: Adict) -> CovarianceMoments:
    lags = parse_lags(options.covariance.kwargs)
    n_processes = options.covariance.kwargs.pop("n_processes")
    pool = Pool(n_processes)
    cov_estimators = pool.map(partial(get_cov_estimators, options=options,
                                    lags=lags), options.trajectory_paths)

    # for input_path in options.trajectory_paths:
    #     ftraj = get_data(input_path, options)
    #     cov_est = calculate_covariance(ftraj, options.covariance, lags)
    #     cov_estimators.append(cov_est)
    cov_estimator = sum(cov_estimators[1:], cov_estimators[0])
    return cov_estimator`
    
    This way it is multiprocessed within one folder. However, right now we use this batching thing which creates these different folders, but if we have the multiprocessing this is not necessary anymore, right?

**Comment by RobertArbon** [comment]
we could - but that means we'll have to write separate code for each module.  I was thinking that we could modify/add to the `run` command in `foam.py` entry point.  

In `foam.py` the 'run` function decides on what module it needs and calls it, giving the config file as an input.  If you give `foam run` 100 config files, it runs them all in serial. I'm thinking we should use multiprocessing at that level.

**Comment by amardt** [comment]
Okay, so I changed it now that you can specify the number of processes as a run option. My question is, what should be the default value? Should it be a single thread or as many the os can find?

**Comment by RobertArbon** [comment]
We should have the default be one. 

Re: the folders - I'm happy to remove this level or organisation if it fulfils a need.  Keeping the input (and potential other outputs) separate does seem useful and is what @boscoh  suggested.  But happy to change this.

**Comment by RobertArbon** [comment]
This has been sorted with https://github.com/RedesignScience/foam/pull/27
